pub mod cache;
pub mod diff;
pub mod dirs;
pub mod fileindex;
pub mod fuzzy;
pub mod git;
pub mod highlight;
pub mod index;
pub mod media;
pub mod outline;
pub mod paths;
pub mod pr;
pub mod scan;
pub mod search;
pub mod settings;
pub mod symbols;
pub mod symindex;
pub mod text;
pub mod trigram;
pub mod watch;

pub use index::{FileEntry, FileMeta, Index, Window, WindowLine};
