#!/usr/bin/env bash
# Write the Homebrew formula for a release from its checksums.txt (BACKEND.md B8).
# Usage: scripts/gen-homebrew-formula.sh <version> <download-base-url> <checksums.txt> [out.rb]
#   <download-base-url> is where ferro-<target>.tar.gz live, e.g.
#   https://github.com/<owner>/ferro/releases/download/v0.2.0
# Publishing the formula to a tap is a separate, board-approved step; this only renders it.
set -euo pipefail

VERSION="${1:?version}"
BASE="${2:?download base url}"
SUMS="${3:?checksums.txt}"
OUT="${4:-packaging/homebrew/ferro.rb}"

sha() {
  local file="ferro-$1.tar.gz" sum
  sum="$(awk -v f="$file" '$2 == f || $2 == "*" f { print $1 }' "$SUMS")"
  if [[ ! "$sum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: no SHA-256 for $file in $SUMS" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

case "$BASE" in https://*) ;; *) echo "error: the download base URL must be https" >&2; exit 1 ;; esac
BASE="${BASE%/}"

cat > "$OUT" <<RUBY
# Generated by scripts/gen-homebrew-formula.sh for ferro ${VERSION}. Do not edit by hand.
class Ferro < Formula
  desc "Fast local code review: browse, diff, review PRs, and ask AI about any repository"
  homepage "${BASE%%/releases/*}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/ferro-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "${BASE}/ferro-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/ferro-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$(sha aarch64-unknown-linux-musl)"
    end
    on_intel do
      url "${BASE}/ferro-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-musl)"
    end
  end

  def install
    bin.install "ferro"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ferro --version")
  end
end
RUBY
echo "wrote $OUT"
